import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "../styles/globals.css";
import ReduxProvider from "../components/redux-provider";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Browser Extension Manager UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body
          className={`${notoSans.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
