import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "../styles/globals.css";
import ReduxProvider from "../components/redux-provider";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Browser Extension Manager UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ReduxProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <script
            dangerouslySetInnerHTML={{
              __html: `
                (function() {
                  try {
                    const theme = localStorage.getItem('theme');
                    const root = document.documentElement;
                    
                    if (theme === 'dark' || theme === 'light') {
                      root.classList.add(theme);
                    } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                      root.classList.add('dark');
                    } else {
                      root.classList.add('light');
                    }
                    
                    if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                      root.style.backgroundColor = '#091540';
                    }
                  } catch (e) {}
                })();
              `,
            }}
          />
        </head>
        <body
          className={`${notoSans.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
